---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl2
spec:
  replicas: 5
  selector:
    matchLabels:
      page: page1
  template:
    metadata:
      labels:
        page: page1
    spec:
      containers:
        - name: cont1
          image: harikrishna7/project1:one
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: svc2
spec:
  type: LoadBalancer
  selector:
    page: page1
  ports:
    - port: 80
      targetPort: 80